#+feature dynamic-literals
package main

// Ocean Circuit — A naval shipping economy game.
// Built with Odin + Raylib + ImGui. Map is loaded from CSV files
// generated by tools/generate_map.py. The world scrolls over a
// tiled sea texture, and ImGui handles HUD/info panels.

import rlimgui "../lib/imgui_impl_raylib"
import imgui "../lib/odin-imgui"
import "core:fmt"
import "core:math"
import rl "vendor:raylib"

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

MAX_ISLANDS :: 48
MAX_TILES :: 16000
TILE_SIZE :: 32
MAP_WIDTH :: 4000
MAP_HEIGHT :: 3250

MAP_CSV_PATH :: "assets/data/map.csv"
META_CSV_PATH :: "assets/data/metadata.csv"
PORTS_CSV_PATH :: "assets/data/ports.csv"
ISLANDS_CSV_PATH :: "assets/data/islands.csv"

// ---------------------------------------------------------------------------
// Resource types
// ---------------------------------------------------------------------------

// ResourceType enumerates the cargo/production types available on islands.
ResourceType :: enum {
	WOOD,
	FISH,
	ORE,
	METAL,
	OIL,
	LUXURY,
	PORT,
}

resource_names := [?]cstring{"Wood", "Fish", "Ore", "Metal", "Oil", "Luxury", "Port"}

resource_colors := [?]rl.Color {
	{139, 90, 43, 255}, // WOOD
	{70, 130, 180, 255}, // FISH
	{128, 128, 128, 255}, // ORE
	{192, 192, 192, 255}, // METAL
	{30, 30, 30, 255}, // OIL
	{255, 215, 0, 255}, // LUXURY
	{0, 220, 200, 255}, // PORT
}

// PORT_COLOR — teal-ish brown, distinct from island resource colors.
PORT_COLOR :: rl.Color{0, 180, 160, 255}
PORT_HIGHLIGHT :: rl.Color{0, 220, 200, 255}

// resource_from_char maps a single-character CSV code to its ResourceType.
resource_from_char :: proc(c: byte) -> ResourceType {
	switch c {
	case 'W':
		return .WOOD
	case 'F':
		return .FISH
	case 'O':
		return .ORE
	case 'M':
		return .METAL
	case 'L':
		return .LUXURY
	case 'P':
		return .PORT
	case:
		return .ORE
	}
}

// ---------------------------------------------------------------------------
// Core data structures
// ---------------------------------------------------------------------------

// Tile represents a single grid cell position in the map.
Tile :: struct {
	gx:      i32, // grid-x coordinate in the tile grid
	gy:      i32, // grid-y coordinate in the tile grid
	is_port: bool,
}

// Island holds all runtime state for a single island: its position,
// production info, warehouse, dock level, and the list of tiles that
// form its landmass.
Island :: struct {
	id:         int,
	pos:        rl.Vector2,
	name:       [32]u8,
	name_len:   int,
	production: ResourceType,
	rate:       f32,
	warehouse:  f32,
	max_ware:   f32,
	dock_level: int,
	radius:     f32,
	tiles:      [MAX_TILES]Tile,
	tile_count: int,
	port_count: int,
}

// MapCell is a raw character from the CSV grid (reserved for future use).
MapCell :: struct {
	ch: byte,
}

// MapGrid holds the full CSV map data as a 2D array of tile characters.
MapGrid :: struct {
	cells:  [MAP_HEIGHT][MAP_WIDTH]byte,
	width:  int,
	height: int,
}

// ---------------------------------------------------------------------------
// Flood fill — groups contiguous grid cells into islands
// ---------------------------------------------------------------------------

// flood_fill_islands scans the grid and uses BFS to group adjacent
// non-water cells into distinct islands. Port positions are loaded
// separately from a ports CSV — no 'P' tiles in the grid.
// Returns the number of islands found.
flood_fill_islands :: proc(
	grid: ^MapGrid,
	islands: ^[MAX_ISLANDS]Island,
	metas: [MAX_ISLANDS]IslandMeta,
	meta_count: int,
) -> int {
	visited_data := make([]bool, MAP_HEIGHT * MAP_WIDTH)
	defer delete(visited_data)

	visited_at :: proc(visited: []bool, x, y: int) -> ^bool {
		return &visited[y * MAP_WIDTH + x]
	}

	island_count := 0
	dirs := [4][2]int{{1, 0}, {-1, 0}, {0, 1}, {0, -1}}

	for y in 0 ..< grid.height {
		for x in 0 ..< grid.width {
			if visited_at(visited_data, x, y)^ {continue}
			if grid.cells[y][x] == '.' {continue}
			if island_count >= MAX_ISLANDS {break}

			start_char := grid.cells[y][x]
			resource := resource_from_char(start_char)

			island := &islands[island_count]
			island.id = island_count
			island.production = resource
			island.warehouse = 0
			island.port_count = 0

			// BFS queue
			queue: [MAX_TILES][2]int
			head := 0
			tail := 0

			queue[tail] = {x, y}
			tail += 1
			visited_at(visited_data, x, y)^ = true

			min_x, max_x := x, x
			min_y, max_y := y, y

			for head < tail && island.tile_count < MAX_TILES {
				cx := queue[head][0] // current BFS cell x
				cy := queue[head][1] // current BFS cell y
				head += 1

				island.tiles[island.tile_count] = {i32(cx), i32(cy), false}
				island.tile_count += 1

				if cx < min_x {min_x = cx}
				if cx > max_x {max_x = cx}
				if cy < min_y {min_y = cy}
				if cy > max_y {max_y = cy}

				for d in dirs { 	// d = direction offset {dx, dy}
					nx := cx + d[0] // neighbor x
					ny := cy + d[1] // neighbor y
					if nx < 0 || nx >= grid.width || ny < 0 || ny >= grid.height {
						continue
					}
					if visited_at(visited_data, nx, ny)^ {continue}
					if grid.cells[ny][nx] != start_char {continue}

					visited_at(visited_data, nx, ny)^ = true
					if tail < MAX_TILES {
						queue[tail] = {nx, ny}
						tail += 1
					}
				}
			}

			// Center position in world space
			center_x := f32(min_x + max_x) / 2.0 * f32(TILE_SIZE)
			center_y := f32(min_y + max_y) / 2.0 * f32(TILE_SIZE)
			island.pos = {center_x, center_y}

			// Bounding radius for label placement
			half_w := f32(max_x - min_x) / 2.0 * f32(TILE_SIZE)
			half_h := f32(max_y - min_y) / 2.0 * f32(TILE_SIZE)
			island.radius = math.max(half_w, half_h)

			// Apply metadata if this island has a matching entry
			for m in 0 ..< meta_count {
				if metas[m].id == island_count {
					island.production = metas[m].production
					island.rate = metas[m].rate
					island.max_ware = metas[m].max_ware
					island.dock_level = metas[m].dock_level

					for j in 0 ..< metas[m].name_len {
						island.name[j] = metas[m].name[j]
					}
					island.name_len = metas[m].name_len
					break
				}
			}

			// Fallback defaults when no metadata matched
			if island.name_len == 0 {
				name_buf := fmt.tprintf("Island %d", island_count)
				n := min(len(name_buf), 31)
				for j in 0 ..< n {
					island.name[j] = name_buf[j]
				}
				island.name_len = n
				island.rate = 2.0
				island.max_ware = 100
				island.dock_level = 2
			}

			island_count += 1
		}
	}

	return island_count
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

// get_name returns a null-terminated cstring of the island's name.
get_name :: proc(island: Island) -> cstring {
	buf: [33]u8
	for j in 0 ..< island.name_len {
		buf[j] = island.name[j]
	}
	buf[island.name_len] = 0
	return cstring(&buf[0])
}

// ---------------------------------------------------------------------------
// Application state
// ---------------------------------------------------------------------------

// Player tracks the player's on-screen position and movement parameters.
Player :: struct {
	x:     f32,
	y:     f32,
	speed: f32,
	size:  f32,
}

// types of water vehicles
ShipTypes :: enum {
	EXPLORER_SHIP,
	SMALL_CARGO_SHIP,
	MEDIUM_CARGO_SHIP,
	LARGE_CARGO_SHIP,
	ASSIST_SMALL_WAR_SHIP,
	ASSIST_MEDIUM_WAR_SHIP,
	ASSIST_LARGE_WAR_SHIP,
	EXPLORER_MEDIUM_SHIP,
	FISHING_SHIP,
	OIL_SHIP_SMALL,
	OIL_SHIP_MEDIUM,
	OIL_SHIP_LARGE,
	SUPPLIES_SMALL_SHIP,
	SUPPLIES_MEDIUM_SHIP,
	SUPPLIES_LARGE_SHIP,
	PATROL_BOARD,
	FRIGATE,
	DESTROYER,
	CRUISER,
	BATTLESHIP,
	PIRATE_SHIP_SMALL, // cannot be owned by player
	PIRATE_SHIP_MEDIUM, // cannot be owned by player
	PIRATE_SHIP_LARGE, // cannot be owned by player
}

// ShipStats holds the base attributes for each ship type.
// Indexed by ShipTypes — add new variants at the matching position.
ShipStats :: struct {
	health:        f32,
	value:         f32,
	speed:         f32, // world-units per second
	cargo_space:   f32, // cargo capacity
	fuel_capacity: f32, // maximum fuel storage
	sensor_range:  f32, // detection/exploration range
}

// ship_stats is the single source of truth for all ship base stats.
// health, value, speed, cargo, fuel, sensors
ship_stats := map[ShipTypes]ShipStats {
	.EXPLORER_SHIP          = {100, 0, 180, 50, 100, 1000}, // fast scout
	.SMALL_CARGO_SHIP       = {140, 5_000, 120, 500, 900, 300},
	.MEDIUM_CARGO_SHIP      = {180, 18_000, 100, 1500, 1500, 400},
	.LARGE_CARGO_SHIP       = {240, 60_000, 70, 5000, 3000, 500}, // slow but massive hold
	.ASSIST_SMALL_WAR_SHIP  = {300, 10_000, 140, 150, 10, 700},
	.ASSIST_MEDIUM_WAR_SHIP = {600, 35_000, 120, 300, 200, 800},
	.ASSIST_LARGE_WAR_SHIP  = {1000, 120_000, 100, 600, 300, 1000},
	.EXPLORER_MEDIUM_SHIP   = {170, 15_000, 160, 300, 200, 1200},
	.FISHING_SHIP           = {120, 0, 120, 800, 800, 250},
	.OIL_SHIP_SMALL         = {180, 50_000, 100, 2000, 1500, 300},
	.OIL_SHIP_MEDIUM        = {220, 150_000, 85, 6000, 3000, 350},
	.OIL_SHIP_LARGE         = {280, 500_000, 70, 15000, 6000, 400},
	.SUPPLIES_SMALL_SHIP    = {130, 8_000, 130, 700, 1000, 300},
	.SUPPLIES_MEDIUM_SHIP   = {170, 30_000, 110, 2500, 2000, 350},
	.SUPPLIES_LARGE_SHIP    = {220, 100_000, 90, 7000, 4000, 400},
	.PATROL_BOARD           = {220, 7_500, 150, 100, 90, 600},
	.FRIGATE                = {500, 80_000, 160, 250, 150, 900},
	.DESTROYER              = {900, 220_000, 140, 400, 250, 1000},
	.CRUISER                = {1500, 450_000, 120, 800, 400, 1200},
	.BATTLESHIP             = {2500, 1_000_000, 60, 1000, 800, 1500},
	.PIRATE_SHIP_SMALL      = {150, 0, 130, 300, 700, 400},
	.PIRATE_SHIP_MEDIUM     = {350, 0, 110, 800, 1500, 500},
	.PIRATE_SHIP_LARGE      = {700, 0, 90, 2000, 2500, 600},
}

// unassisted ships have risk of death
// even when assisted the damage will be divided into percentages,
// e.g. small cargo assisted by small assist: assist takes 60% damage, cargo 40%.
// bigger assist ships guarantee better ratios.

// ShipState tracks whether a ship is idle, sailing, or docked.
ShipState :: enum {
	IDLE,
	SAILING,
	DOCKED,
}

// Ship is a moveable vessel that can only travel in water.
Ship :: struct {
	x:      f32,
	y:      f32,
	speed:  f32,
	angle:  f32,
	type:   ShipTypes,
	health: f32,
	value:  f32,
	state:  ShipState,
	dest_x: f32, // destination world-x (used when SAILING)
	dest_y: f32, // destination world-y (used when SAILING)
}

MAX_SHIPS :: 64

// App is the top-level game state — islands, grid, camera, economy, and player.
App :: struct {
	islands:         [MAX_ISLANDS]Island,
	island_count:    int,
	grid:            MapGrid,
	camera:          rl.Camera2D,
	selected:        int,
	money:           f32,
	time_day:        f32,
	scroll_tex:      rl.Texture2D,
	bg_color:        rl.Color,
	scroll_x:        f32,
	scroll_y:        f32,
	player:          Player,
	ships:           [MAX_SHIPS]Ship,
	world_economy:   f32, // used to calculate total trading in game , we already have user money so percentage can be calculated via it.
	ship_pos_timer:  f32, // counts up to 5s then resets, gates position display refresh
	sailing_count:   int, // cached count of SAILING ships
	sailing_grid_xs: [MAX_SHIPS]int, // cached grid-x of each sailing ship
	sailing_grid_ys: [MAX_SHIPS]int, // cached grid-y of each sailing ship
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

// main initialises the window, loads the map and metadata, then runs the
// game loop: update → render → ImGui → input.
main :: proc() {
	rl.SetConfigFlags({.WINDOW_RESIZABLE, .WINDOW_ALWAYS_RUN})
	rl.InitWindow(1280, 720, "Ocean Circuit")
	defer rl.CloseWindow()
	rl.SetTargetFPS(60)

	imgui.CreateContext(nil)
	defer imgui.DestroyContext(nil)
	io := imgui.GetIO()
	io.ConfigFlags |= {.NavEnableKeyboard}
	rlimgui.init()
	defer rlimgui.shutdown()

	// Load map from CSV
	app := new(App)
	defer free(app)
	if !load_map_csv(MAP_CSV_PATH, &app.grid) {
		fmt.println("ERROR: Could not load", MAP_CSV_PATH)
		return
	}

	// Load island tiles from CSV (no flood fill needed)
	app.island_count = load_islands_csv(ISLANDS_CSV_PATH, &app.grid, &app.islands)

	// Load metadata (names, rates, dock levels)
	metas: [MAX_ISLANDS]IslandMeta
	meta_count: int
	load_metadata_csv(META_CSV_PATH, &metas, &meta_count)

	// Apply metadata to islands
	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		for m in 0 ..< meta_count {
			if metas[m].id == island.id {
				island.production = metas[m].production
				island.rate = metas[m].rate
				island.max_ware = metas[m].max_ware
				island.dock_level = metas[m].dock_level
				for j in 0 ..< metas[m].name_len {
					island.name[j] = metas[m].name[j]
				}
				island.name_len = metas[m].name_len
				break
			}
		}
	}

	// Load port positions and mark tiles
	load_ports_csv(PORTS_CSV_PATH, &app.islands, app.island_count)

	app.money = 1000
	app.selected = -1

	// Spawn the player on the PORT island (fallback: first island)
	app.player.size = 20
	app.player.speed = 200
	spawn_island := -1
	for i in 0 ..< app.island_count {
		if app.islands[i].production == .PORT {
			spawn_island = i
			break
		}
	}
	if spawn_island < 0 && app.island_count > 0 {
		spawn_island = 0
	}

	if spawn_island >= 0 {
		spawn_name := "spawn"
		n := min(len(spawn_name), 31)
		for j in 0 ..< n {
			app.islands[spawn_island].name[j] = spawn_name[j]
		}
		app.islands[spawn_island].name_len = n
	}

	if spawn_island >= 0 && app.islands[spawn_island].tile_count > 0 {
		// Place player on first tile
		t := app.islands[spawn_island].tiles[0]
		app.player.x = f32(t.gx) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
		app.player.y = f32(t.gy) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2

		// Init explorer ship with base stats from lookup table
		ship := &app.ships[0]
		ship.type = .EXPLORER_SHIP
		ship.health = ship_stats[.EXPLORER_SHIP].health
		ship.value = ship_stats[.EXPLORER_SHIP].value
		ship.speed = ship_stats[.EXPLORER_SHIP].speed * 15 // TODO : remove 50 from here , only for testing

		// Find a water tile adjacent to the spawn island's port
		dirs := [4][2]int{{1, 0}, {-1, 0}, {0, 1}, {0, -1}}
		for ti in 0 ..< app.islands[spawn_island].tile_count {
			if !app.islands[spawn_island].tiles[ti].is_port {continue}
			port_gx := app.islands[spawn_island].tiles[ti].gx
			port_gy := app.islands[spawn_island].tiles[ti].gy
			for d in dirs {
				water_gx := port_gx + i32(d[0])
				water_gy := port_gy + i32(d[1])
				if water_gx >= 0 &&
				   water_gx < i32(app.grid.width) &&
				   water_gy >= 0 &&
				   water_gy < i32(app.grid.height) &&
				   app.grid.cells[water_gy][water_gx] == '.' {
					ship.x = f32(water_gx) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
					ship.y = f32(water_gy) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
					ship.state = .DOCKED
					break
				}
			}
			if ship.state == .DOCKED {break}
		}
	}

	// Camera: centred on player, half-zoom
	app.camera.offset = {640, 360}
	app.camera.target = {app.player.x, app.player.y}
	app.camera.rotation = 0
	app.camera.zoom = 0.5

	// Tiled sea texture
	app.scroll_tex = rl.LoadTexture("assets/img/sea_texture.png")
	defer rl.UnloadTexture(app.scroll_tex)

	app.bg_color = {10, 20, 50, 255}

	fmt.printf("Loaded %d islands from %s\n", app.island_count, ISLANDS_CSV_PATH)

	// Main game loop
	for !rl.WindowShouldClose() {
		update_player(app)
		update_ship(app)
		update_camera(app)
		app.time_day += rl.GetFrameTime() / 60.0
		app.ship_pos_timer += rl.GetFrameTime()
		if app.ship_pos_timer >= 5.0 {
			app.ship_pos_timer = 0
			app.sailing_count = 0
			for i in 0 ..< MAX_SHIPS {
				if app.ships[i].state == .SAILING {
					app.sailing_grid_xs[app.sailing_count] = int(app.ships[i].x / f32(TILE_SIZE))
					app.sailing_grid_ys[app.sailing_count] = int(app.ships[i].y / f32(TILE_SIZE))
					app.sailing_count += 1
				}
			}
		}

		rl.BeginDrawing()
		rl.ClearBackground(app.bg_color)

		rl.BeginMode2D(app.camera)
		draw_water(app)
		draw_islands(app)
		draw_ship(app)
		draw_player(app)
		rl.EndMode2D()

		rlimgui.begin()
		draw_hud(app)
		rlimgui.end()

		if rl.IsMouseButtonPressed(.LEFT) && !imgui.GetIO().WantCaptureMouse {
			handle_click(app)
		}

		rl.EndDrawing()
	}
}

// ---------------------------------------------------------------------------
// Player movement
// ---------------------------------------------------------------------------

// is_water returns true if the world-space position falls on a water tile
// (or outside the grid bounds).
is_water :: proc(grid: ^MapGrid, world_x, world_y: f32) -> bool {
	gx := int(world_x / f32(TILE_SIZE)) // grid-x from world position
	gy := int(world_y / f32(TILE_SIZE)) // grid-y from world position
	if gx < 0 || gx >= grid.width || gy < 0 || gy >= grid.height {
		return true
	}
	return grid.cells[gy][gx] == '.'
}

// update_player reads WASD input and moves the player, blocking
// movement into non-water tiles.
update_player :: proc(app: ^App) {
	dt := rl.GetFrameTime()
	speed := app.player.speed * dt
	dx: f32 = 0
	dy: f32 = 0

	if rl.IsKeyDown(.W) {dy -= speed}
	if rl.IsKeyDown(.S) {dy += speed}
	if rl.IsKeyDown(.A) {dx -= speed}
	if rl.IsKeyDown(.D) {dx += speed}

	// Try X then Y independently so diagonal movement slides along walls
	new_x := app.player.x + dx
	if !is_water(&app.grid, new_x, app.player.y) {
		app.player.x = new_x
	}

	new_y := app.player.y + dy
	if !is_water(&app.grid, app.player.x, new_y) {
		app.player.y = new_y
	}
}

// update_ship moves ships toward their destination when sailing.
update_ship :: proc(app: ^App) {
	dt := rl.GetFrameTime()
	for i in 0 ..< MAX_SHIPS {
		ship := &app.ships[i]
		if ship.state != .SAILING {continue}

		dx := ship.dest_x - ship.x
		dy := ship.dest_y - ship.y
		dist := math.sqrt(dx * dx + dy * dy)

		// Arrived — snap to destination and dock
		if dist < 2.0 {
			ship.x = ship.dest_x
			ship.y = ship.dest_y
			ship.state = .DOCKED
			continue
		}

		// Normalize direction and move at ship's speed
		nx := dx / dist
		ny := dy / dist
		step := ship.speed * dt
		if step > dist {step = dist}
		ship.x += nx * step
		ship.y += ny * step

		// Rotate to face movement direction (degrees, 0 = right)
		ship.angle = math.atan2(ny, nx) * (180.0 / math.PI)
	}
}

// ---------------------------------------------------------------------------
// Camera — free-form panning with arrow keys, zoom with scroll wheel
// ---------------------------------------------------------------------------

// update_camera centres the camera on the player and adjusts zoom
// with the mouse wheel (clamped to 0.5–1.5).
update_camera :: proc(app: ^App) {
	app.camera.target = {app.player.x, app.player.y}

	wheel := rl.GetMouseWheelMove()
	if wheel != 0 {
		app.camera.zoom += wheel * 0.05
		if app.camera.zoom < 0.5 {app.camera.zoom = 0.5}
		if app.camera.zoom > 1.5 {app.camera.zoom = 1.5}
	}
}

// ---------------------------------------------------------------------------
// Rendering — viewport culled for performance
// ---------------------------------------------------------------------------

// get_viewport returns the visible world-space rectangle based on the
// current camera position and zoom level.
get_viewport :: proc(app: ^App) -> (min_x, min_y, max_x, max_y: f32) {
	screen_w := f32(rl.GetScreenWidth())
	screen_h := f32(rl.GetScreenHeight())
	half_w := (screen_w / 2) / app.camera.zoom
	half_h := (screen_h / 2) / app.camera.zoom
	min_x = app.camera.target.x - half_w
	min_y = app.camera.target.y - half_h
	max_x = app.camera.target.x + half_w
	max_y = app.camera.target.y + half_h
	return
}

// draw_water tiles the sea texture across the visible viewport, slowly
// scrolling to give a sense of ocean movement.
draw_water :: proc(app: ^App) {
	tex_w := f32(app.scroll_tex.width)
	tex_h := f32(app.scroll_tex.height)

	app.scroll_x += 15 * rl.GetFrameTime()
	app.scroll_y += 10 * rl.GetFrameTime()
	if app.scroll_x >= tex_w {app.scroll_x -= tex_w}
	if app.scroll_y >= tex_h {app.scroll_y -= tex_h}

	vp_min_x, vp_min_y, vp_max_x, vp_max_y := get_viewport(app)
	start_ix := i32(math.floor(vp_min_x / tex_w)) - 1
	start_iy := i32(math.floor(vp_min_y / tex_h)) - 1
	end_ix := i32(math.ceil(vp_max_x / tex_w)) + 1
	end_iy := i32(math.ceil(vp_max_y / tex_h)) + 1

	for ix := start_ix; ix <= end_ix; ix += 1 {
		for iy := start_iy; iy <= end_iy; iy += 1 {
			pos_x := f32(ix) * tex_w - app.scroll_x
			pos_y := f32(iy) * tex_h - app.scroll_y
			rl.DrawTexture(app.scroll_tex, i32(pos_x), i32(pos_y), rl.WHITE)
		}
	}
}

// draw_islands renders every island's tiles and labels.
// Viewport culling skips tiles outside the camera view for performance.
draw_islands :: proc(app: ^App) {
	vp_min_x, vp_min_y, vp_max_x, vp_max_y := get_viewport(app)
	tile_f := f32(TILE_SIZE)

	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		color := resource_colors[island.production]

		// Bounding-box cull entire island if off-screen (with buffer)
		buffer := tile_f * 2
		island_min_x := island.pos.x - island.radius - buffer
		island_max_x := island.pos.x + island.radius + buffer
		island_min_y := island.pos.y - island.radius - buffer
		island_max_y := island.pos.y + island.radius + buffer
		if island_max_x < vp_min_x ||
		   island_min_x > vp_max_x ||
		   island_max_y < vp_min_y ||
		   island_min_y > vp_max_y {
			continue
		}

		// Draw tiles
		for t in 0 ..< island.tile_count {
			tile := &island.tiles[t]
			x := f32(tile.gx) * tile_f
			y := f32(tile.gy) * tile_f

			// Selection glow
			if app.selected == i {
				rl.DrawRectangle(
					i32(x) - 1,
					i32(y) - 1,
					i32(tile_f) + 2,
					i32(tile_f) + 2,
					{255, 255, 100, 60},
				)
			}

			// Port tiles get a distinct colour; resource tiles keep theirs
			tile_color := color
			if tile.is_port {
				tile_color = PORT_COLOR
			}

			rl.DrawRectangleV({x, y}, {tile_f, tile_f}, tile_color)
			rl.DrawRectangleLinesEx({x, y, tile_f, tile_f}, 2, {20, 20, 20, 200})
		}

		// Labels (only when roughly on-screen)
		if island.pos.x >= vp_min_x - 200 &&
		   island.pos.x <= vp_max_x + 200 &&
		   island.pos.y >= vp_min_y - 100 &&
		   island.pos.y <= vp_max_y + 100 {

			name := get_name(island^)
			text_w := rl.MeasureText(name, 32)
			name_x := i32(island.pos.x) - text_w / 2
			name_y := i32(island.pos.y + island.radius + 16)
			rl.DrawText(name, name_x + 2, name_y + 2, 32, {0, 0, 0, 200})
			rl.DrawText(name, name_x, name_y, 32, {255, 255, 255, 255})

			res_name := resource_names[island.production]
			res_w := rl.MeasureText(res_name, 24)
			res_x := i32(island.pos.x) - res_w / 2
			res_y := i32(island.pos.y - 20)
			rl.DrawText(res_name, res_x + 2, res_y + 2, 24, {0, 0, 0, 200})
			rl.DrawText(res_name, res_x, res_y, 24, {255, 255, 255, 255})
		}
	}
}

// draw_ship renders the ship as a pink rectangle, 3 tiles tall and 1 tile wide,
// placed at the port. The ship is static — not controlled by the player.
draw_ship :: proc(app: ^App) {
	tile_f := f32(TILE_SIZE)
	ship_w := tile_f
	ship_h := tile_f * 3

	origin := rl.Vector2{ship_w / 2, ship_h / 2}
	rect := rl.Rectangle{app.ships[0].x - origin.x, app.ships[0].y - origin.y, ship_w, ship_h}

	rl.DrawRectanglePro(rect, origin, app.ships[0].angle, {255, 100, 150, 255})
	rl.DrawRectangleLinesEx(rect, 2, {200, 60, 100, 255})
}

// draw_player renders the player as a small red square at its center position.
draw_player :: proc(app: ^App) {
	s := app.player.size
	rl.DrawRectangleV({app.player.x - s / 2, app.player.y - s / 2}, {s, s}, {220, 30, 30, 255})
}

// ---------------------------------------------------------------------------
// HUD — ImGui panels
// ---------------------------------------------------------------------------

// draw_hud draws the top-left info panel and, when an island is selected,
// a detail panel showing its production, warehouse, and dock stats.
draw_hud :: proc(app: ^App) {
	// Info panel
	imgui.SetNextWindowSize({260, 0}, .FirstUseEver)
	imgui.SetNextWindowPos({10, 10}, .FirstUseEver)
	if imgui.Begin("Info") {
		imgui.Text("Map: %dx%d", MAP_WIDTH, MAP_HEIGHT)
		imgui.Text("Islands: %d", app.island_count)
		imgui.TextColored({0.2, 1, 0.2, 1}, "Money: $%d", i32(app.money))
		imgui.Text("Day: %.1f", app.time_day)
		imgui.Text("Zoom: %.0f%%", app.camera.zoom * 100)
		imgui.Separator()
		imgui.TextDisabled("WASD: move character")
		imgui.TextDisabled("Scroll: zoom")
		imgui.TextDisabled("Click: select island or ship")
		imgui.TextDisabled("Scroll: zoom")
	}
	imgui.End()

	// Sailing ships panel — shows count and positions, refreshes every 5s
	imgui.SetNextWindowSize({260, 0}, .FirstUseEver)
	imgui.SetNextWindowPos({10, 200}, .FirstUseEver)
	if imgui.Begin("Sailing Ships") {
		imgui.Text("En route: %d", app.sailing_count)
		if app.sailing_count > 0 {
			imgui.Separator()
			for i in 0 ..< app.sailing_count {
				imgui.Text("#%d  grid(%d, %d)", i, app.sailing_grid_xs[i], app.sailing_grid_ys[i])
			}
		}
	}
	imgui.End()

	// Selected-island detail panel
	if app.selected >= 0 && app.selected < app.island_count {
		island := &app.islands[app.selected]
		name := get_name(island^)

		imgui.SetNextWindowSize({280, 0}, .FirstUseEver)
		imgui.SetNextWindowPos({10, 120}, .FirstUseEver)
		if imgui.Begin("Island") {
			imgui.Text("ID: %d | %s", island.id, name)
			imgui.Separator()
			imgui.Text("Produces: %s", resource_names[island.production])
			imgui.Text("Rate: %.1f/day", island.rate)
			imgui.Text("Storage: %.0f / %.0f", island.warehouse, island.max_ware)
			imgui.Text("Dock Level: %d", island.dock_level)
			imgui.Text("Tiles: %d", island.tile_count)

			if island.port_count > 0 {
				imgui.Separator()
				imgui.TextColored({0, 0.9, 0.8, 1}, "Port Tiles: %d", island.port_count)
				imgui.TextDisabled("Docks along the coast")
			}
		}
		imgui.End()
	}

	// Selected-ship detail panel
	if app.selected == -2 {
		imgui.SetNextWindowSize({280, 0}, .FirstUseEver)
		imgui.SetNextWindowPos({10, 120}, .FirstUseEver)
		if imgui.Begin("Ship") {
			stats := ship_stats[app.ships[0].type]
			imgui.TextColored({1, 0.4, 0.6, 1}, "%v", app.ships[0].type)
			imgui.Separator()
			imgui.Text("Health: %.0f / %.0f", app.ships[0].health, stats.health)
			imgui.Text("Speed: %.0f", app.ships[0].speed)
			imgui.Text("Value: $%d", i32(stats.value))
		}
		imgui.End()
	}
}

// ---------------------------------------------------------------------------
// Input — click to select an island
// ---------------------------------------------------------------------------

// handle_click converts the mouse position to world space and checks
// every island tile for a hit, selecting the first match.
handle_click :: proc(app: ^App) {
	mouse := rl.GetScreenToWorld2D(rl.GetMousePosition(), app.camera)
	app.selected = -1
	tile_f := f32(TILE_SIZE)

	// Check ship hit
	ship_w := tile_f
	ship_h := tile_f * 3
	if mouse.x >= app.ships[0].x - ship_w / 2 &&
	   mouse.x <= app.ships[0].x + ship_w / 2 &&
	   mouse.y >= app.ships[0].y - ship_h / 2 &&
	   mouse.y <= app.ships[0].y + ship_h / 2 {
		app.selected = -2
		return
	}

	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		for t in 0 ..< island.tile_count {
			tile := &island.tiles[t]
			tx := f32(tile.gx) * tile_f // tile world-x position
			ty := f32(tile.gy) * tile_f // tile world-y position
			if mouse.x >= tx && mouse.x <= tx + tile_f && mouse.y >= ty && mouse.y <= ty + tile_f {
				app.selected = i
				return
			}
		}
	}
}
