package main

// Ocean Circuit — A naval shipping economy game.
// Built with Odin + Raylib + ImGui. Map is loaded from CSV files
// generated by tools/generate_map.py. The world scrolls over a
// tiled sea texture, and ImGui handles HUD/info panels.

import rlimgui "../lib/imgui_impl_raylib"
import imgui "../lib/odin-imgui"
import "core:fmt"
import "core:math"
import "core:os"
import rl "vendor:raylib"

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

MAX_ISLANDS :: 48
MAX_TILES :: 16000
TILE_SIZE :: 32
MAP_WIDTH :: 4000
MAP_HEIGHT :: 3250

MAP_CSV_PATH :: "assets/data/map.csv"
META_CSV_PATH :: "assets/data/metadata.csv"
PORTS_CSV_PATH :: "assets/data/ports.csv"
ISLANDS_CSV_PATH :: "assets/data/islands.csv"

// ---------------------------------------------------------------------------
// Resource types
// ---------------------------------------------------------------------------

// ResourceType enumerates the cargo/production types available on islands.
ResourceType :: enum {
	WOOD,
	FISH,
	ORE,
	METAL,
	OIL,
	LUXURY,
	PORT,
}

resource_names := [?]cstring{"Wood", "Fish", "Ore", "Metal", "Oil", "Luxury", "Port"}

resource_colors := [?]rl.Color {
	{139, 90, 43, 255},   // WOOD
	{70, 130, 180, 255},  // FISH
	{128, 128, 128, 255}, // ORE
	{192, 192, 192, 255}, // METAL
	{30, 30, 30, 255},    // OIL
	{255, 215, 0, 255},   // LUXURY
	{0, 220, 200, 255},   // PORT
}

// PORT_COLOR — teal-ish brown, distinct from island resource colors.
PORT_COLOR :: rl.Color{0, 180, 160, 255}
PORT_HIGHLIGHT :: rl.Color{0, 220, 200, 255}

// resource_from_char maps a single-character CSV code to its ResourceType.
resource_from_char :: proc(c: byte) -> ResourceType {
	switch c {
	case 'W': return .WOOD
	case 'F': return .FISH
	case 'O': return .ORE
	case 'M': return .METAL
	case 'L': return .LUXURY
	case 'P': return .PORT
	case:    return .ORE
	}
}

// ---------------------------------------------------------------------------
// Core data structures
// ---------------------------------------------------------------------------

// Tile represents a single grid cell position in the map.
Tile :: struct {
	gx:      i32,
	gy:      i32,
	is_port: bool,
}

// Island holds all runtime state for a single island: its position,
// production info, warehouse, dock level, and the list of tiles that
// form its landmass.
Island :: struct {
	id:          int,
	pos:         rl.Vector2,
	name:        [32]u8,
	name_len:    int,
	production:  ResourceType,
	rate:        f32,
	warehouse:   f32,
	max_ware:    f32,
	dock_level:  int,
	radius:      f32,
	tiles:       [MAX_TILES]Tile,
	tile_count:  int,
	port_count:  int,
}

// MapCell is a raw character from the CSV grid (reserved for future use).
MapCell :: struct {
	ch: byte,
}

// MapGrid holds the full CSV map data as a 2D array of tile characters.
MapGrid :: struct {
	cells:  [MAP_HEIGHT][MAP_WIDTH]byte,
	width:  int,
	height: int,
}

// ---------------------------------------------------------------------------
// CSV loading — fully manual, no library dependencies
// ---------------------------------------------------------------------------

// read_file reads an entire file into a heap-allocated buffer.
// Returns nil on error.
read_file :: proc(path: string) -> (data: []byte) {
	handle, err := os.open(path)
	if err != nil {return nil}
	defer os.close(handle)

	buf := make([]byte, 64 * 1024 * 1024)
	total := 0
	for {
		n, read_err := os.read(handle, buf[total:])
		total += n
		if read_err != nil || n == 0 {break}
	}
	return buf[:total]
}

// parse_int parses a simple ASCII integer from a byte slice (supports negative).
parse_int :: proc(s: []byte) -> (v: int, ok: bool) {
	if len(s) == 0 {return 0, false}

	i := 0
	negative := false
	if s[0] == '-' {
		negative = true
		i = 1
	}

	result := 0
	found_digit := false
	for j := i; j < len(s); j += 1 {
		c := s[j]
		if c < '0' || c > '9' {break}
		result = result * 10 + int(c - '0')
		found_digit = true
	}

	if !found_digit {return 0, false}
	if negative {result = -result}
	return result, true
}

// parse_f32 parses a simple ASCII float (e.g. "2.5", "120") from a byte slice.
parse_f32 :: proc(s: []byte) -> (v: f32, ok: bool) {
	if len(s) == 0 {return 0, false}

	str := string(s)
	negative := false
	i := 0
	if str[0] == '-' {
		negative = true
		i = 1
	}

	whole := 0
	decimal := 0
	divisor := f32(1)
	found_digit := false

	for j := i; j < len(str); j += 1 {
		c := str[j]
		if c == '.' {
			for k := j + 1; k < len(str); k += 1 {
				dc := str[k]
				if dc < '0' || dc > '9' {break}
				decimal = decimal * 10 + int(dc - '0')
				divisor *= 10
				found_digit = true
			}
			break
		} else if c >= '0' && c <= '9' {
			whole = whole * 10 + int(c - '0')
			found_digit = true
		} else {
			break
		}
	}

	if !found_digit {return 0, false}

	result := f32(whole) + f32(decimal) / divisor
	if negative {result = -result}
	return result, true
}

// CsvField stores the start/end byte indices of a single CSV field.
CsvField :: struct {
	start: int,
	end:   int,
}

// split_csv_fields splits a line by commas and writes field boundaries
// into the provided slice. Returns the number of fields found.
split_csv_fields :: proc(line: []byte, fields: []CsvField) -> int {
	count := 0
	f_start := 0
	for i in 0 ..< len(line) {
		if line[i] == ',' {
			if count < len(fields) {
				fields[count] = {f_start, i}
				count += 1
			}
			f_start = i + 1
		}
	}
	if count < len(fields) {
		fields[count] = {f_start, len(line)}
		count += 1
	}
	return count
}

// load_map_csv reads the tile grid CSV and populates the MapGrid.
// Returns true on success.
load_map_csv :: proc(path: string, grid: ^MapGrid) -> bool {
	content := read_file(path)
	if len(content) == 0 {return false}
	defer delete(content)

	row := 0
	col := 0
	for b in content {
		if b == '\n' {
			for c := col; c < MAP_WIDTH; c += 1 {
				grid.cells[row][c] = '.'
			}
			row += 1
			col = 0
			if row >= MAP_HEIGHT {break}
		} else if b == '\r' {
			// skip carriage return
		} else if b == ',' {
			col += 1
		} else {
			if row < MAP_HEIGHT && col < MAP_WIDTH {
				grid.cells[row][col] = b
			}
		}
	}

	// Pad final row if file doesn't end with newline
	if col > 0 && row < MAP_HEIGHT {
		for c := col; c < MAP_WIDTH; c += 1 {
			grid.cells[row][c] = '.'
		}
		row += 1
	}

	grid.width = MAP_WIDTH
	grid.height = row
	return true
}

// IslandMeta stores one row from metadata.csv — static island configuration.
IslandMeta :: struct {
	id:         int,
	name:       [32]u8,
	name_len:   int,
	production: ResourceType,
	rate:       f32,
	max_ware:   f32,
	dock_level: int,
	tile_count: int,
}

// load_metadata_csv reads island metadata (names, production rates, etc.)
// and writes results into the metas array.
load_metadata_csv :: proc(path: string, metas: ^[MAX_ISLANDS]IslandMeta, out_count: ^int) {
	content := read_file(path)
	if len(content) == 0 {return}
	defer delete(content)

	row := 0
	line_start := 0
	is_header := true

	for i := 0; i <= len(content); i += 1 {
		is_end := i == len(content)
		is_newline := false
		if !is_end {
			is_newline = content[i] == '\n' || content[i] == '\r'
		}

		if is_end || is_newline {
			if i > line_start && !is_header && row < MAX_ISLANDS {
				line := content[line_start:i]

				// Skip empty lines
				all_whitespace := true
				for b in line {
					if b != ' ' && b != '\t' {
						all_whitespace = false
						break
					}
				}

				if !all_whitespace {
					fields: [16]CsvField
					field_count := split_csv_fields(line, fields[:])

					if field_count >= 8 {
						meta := &metas[row]

						// Column 0: island_id
						if v, ok := parse_int(line[fields[0].start:fields[0].end]); ok {
							meta.id = v
						}

						// Column 1: name (trim surrounding quotes)
						ns := fields[1].start
						ne := fields[1].end
						if ne > ns && line[ns] == '"' {
							ns += 1
							if ne > ns && line[ne - 1] == '"' {
								ne -= 1
							}
						}
						n := min(ne - ns, 31)
						for j in 0 ..< n {
							meta.name[j] = line[ns + j]
						}
						meta.name_len = n

						// Column 2: production character
						if fields[2].end > fields[2].start {
							meta.production = resource_from_char(line[fields[2].start])
						}

						// Column 3: rate
						if v, ok := parse_f32(line[fields[3].start:fields[3].end]); ok {
							meta.rate = v
						}

						// Column 5: max_warehouse
						if v, ok := parse_f32(line[fields[5].start:fields[5].end]); ok {
							meta.max_ware = v
						}

						// Column 6: dock_level
						if v, ok := parse_int(line[fields[6].start:fields[6].end]); ok {
							meta.dock_level = v
						}

						// Column 7: tile_count
						if v, ok := parse_int(line[fields[7].start:fields[7].end]); ok {
							meta.tile_count = v
						}

						row += 1
					}
				}
			}

			if is_header {is_header = false}

			// Handle \r\n line endings
			if !is_end && content[i] == '\r' && i + 1 < len(content) && content[i + 1] == '\n' {
				line_start = i + 2
			} else {
				line_start = i + 1
			}
		}
	}

	out_count^ = row
}

// ---------------------------------------------------------------------------
// Port loading — reads port positions from CSV and marks tiles
// ---------------------------------------------------------------------------

// load_ports_csv reads port positions (island_id, x, y) and marks
// matching tiles as is_port on the corresponding island.
load_ports_csv :: proc(path: string, islands: ^[MAX_ISLANDS]Island, island_count: int) {
	content := read_file(path)
	if len(content) == 0 {return}
	defer delete(content)

	row := 0
	line_start := 0
	is_header := true

	for i := 0; i <= len(content); i += 1 {
		is_end := i == len(content)
		is_newline := false
		if !is_end {
			is_newline = content[i] == '\n' || content[i] == '\r'
		}

		if is_end || is_newline {
			if i > line_start && !is_header {
				line := content[line_start:i]

				all_whitespace := true
				for b in line {
					if b != ' ' && b != '\t' {
						all_whitespace = false
						break
					}
				}

				if !all_whitespace {
					fields: [16]CsvField
					field_count := split_csv_fields(line, fields[:])

					if field_count >= 3 {
						island_id := 0
						px := 0
						py := 0

						if v, ok := parse_int(line[fields[0].start:fields[0].end]); ok {
							island_id = v
						}
						if v, ok := parse_int(line[fields[1].start:fields[1].end]); ok {
							px = v
						}
						if v, ok := parse_int(line[fields[2].start:fields[2].end]); ok {
							py = v
						}

						// Mark the tile as port if island is in range
						if island_id >= 0 && island_id < island_count {
							island := &islands[island_id]
							for t in 0 ..< island.tile_count {
								if island.tiles[t].gx == i32(px) && island.tiles[t].gy == i32(py) {
									island.tiles[t].is_port = true
									island.port_count += 1
									break
								}
							}
						}
					}
				}
			}

			if is_header {is_header = false}

			if !is_end && content[i] == '\r' && i + 1 < len(content) && content[i + 1] == '\n' {
				line_start = i + 2
			} else {
				line_start = i + 1
			}
		}
	}
}

// load_islands_csv reads island tile assignments (island_id, x, y)
// and populates the Island structs directly — no flood fill needed.
// Returns the number of islands loaded.
load_islands_csv :: proc(
	path: string,
	grid: ^MapGrid,
	islands: ^[MAX_ISLANDS]Island,
) -> int {
	content := read_file(path)
	if len(content) == 0 {return 0}
	defer delete(content)

	island_count := 0
	row := 0
	line_start := 0
	is_header := true

	for i := 0; i <= len(content); i += 1 {
		is_end := i == len(content)
		is_newline := false
		if !is_end {
			is_newline = content[i] == '\n' || content[i] == '\r'
		}

		if is_end || is_newline {
			if i > line_start && !is_header {
				line := content[line_start:i]

				all_whitespace := true
				for b in line {
					if b != ' ' && b != '\t' {
						all_whitespace = false
						break
					}
				}

				if !all_whitespace {
					fields: [16]CsvField
					field_count := split_csv_fields(line, fields[:])

					if field_count >= 3 {
						island_id := 0
						px := 0
						py := 0

						if v, ok := parse_int(line[fields[0].start:fields[0].end]); ok {
							island_id = v
						}
						if v, ok := parse_int(line[fields[1].start:fields[1].end]); ok {
							px = v
						}
						if v, ok := parse_int(line[fields[2].start:fields[2].end]); ok {
							py = v
						}

						if island_id >= 0 && island_id < MAX_ISLANDS {
							island := &islands[island_id]

							// Initialize island on first tile
							if island.tile_count == 0 {
								island.id = island_id
								island.production = resource_from_char(grid.cells[py][px])
								island.warehouse = 0
								island.port_count = 0
								if island_id > island_count {
									island_count = island_id
								}
							}

							if island.tile_count < MAX_TILES {
								island.tiles[island.tile_count] = {i32(px), i32(py), false}
								island.tile_count += 1
							}
						}
					}
				}
			}

			if is_header {is_header = false}

			if !is_end && content[i] == '\r' && i + 1 < len(content) && content[i + 1] == '\n' {
				line_start = i + 2
			} else {
				line_start = i + 1
			}
		}
	}

	// Compute center, radius, and count for each island
	for i in 0 ..< island_count + 1 {
		island := &islands[i]
		if island.tile_count == 0 {continue}

		min_x := island.tiles[0].gx
		max_x := island.tiles[0].gx
		min_y := island.tiles[0].gy
		max_y := island.tiles[0].gy

		for t in 1 ..< island.tile_count {
			tx := island.tiles[t].gx
			ty := island.tiles[t].gy
			if tx < min_x {min_x = tx}
			if tx > max_x {max_x = tx}
			if ty < min_y {min_y = ty}
			if ty > max_y {max_y = ty}
		}

		center_x := f32(min_x + max_x) / 2.0 * f32(TILE_SIZE)
		center_y := f32(min_y + max_y) / 2.0 * f32(TILE_SIZE)
		island.pos = {center_x, center_y}

		half_w := f32(max_x - min_x) / 2.0 * f32(TILE_SIZE)
		half_h := f32(max_y - min_y) / 2.0 * f32(TILE_SIZE)
		island.radius = math.max(half_w, half_h)
	}

	return island_count + 1
}

// ---------------------------------------------------------------------------
// Flood fill — groups contiguous grid cells into islands
// ---------------------------------------------------------------------------

// flood_fill_islands scans the grid and uses BFS to group adjacent
// non-water cells into distinct islands. Port positions are loaded
// separately from a ports CSV — no 'P' tiles in the grid.
// Returns the number of islands found.
flood_fill_islands :: proc(
	grid: ^MapGrid,
	islands: ^[MAX_ISLANDS]Island,
	metas: [MAX_ISLANDS]IslandMeta,
	meta_count: int,
) -> int {
	visited_data := make([]bool, MAP_HEIGHT * MAP_WIDTH)
	defer delete(visited_data)

	visited_at :: proc(visited: []bool, x, y: int) -> ^bool {
		return &visited[y * MAP_WIDTH + x]
	}

	island_count := 0
	dirs := [4][2]int{{1, 0}, {-1, 0}, {0, 1}, {0, -1}}

	for y in 0 ..< grid.height {
		for x in 0 ..< grid.width {
			if visited_at(visited_data, x, y)^ {continue}
			if grid.cells[y][x] == '.' {continue}
			if island_count >= MAX_ISLANDS {break}

			start_char := grid.cells[y][x]
			resource := resource_from_char(start_char)

			island := &islands[island_count]
			island.id = island_count
			island.production = resource
			island.warehouse = 0
			island.port_count = 0

			// BFS queue
			queue: [MAX_TILES][2]int
			head := 0
			tail := 0

			queue[tail] = {x, y}
			tail += 1
			visited_at(visited_data, x, y)^ = true

			min_x, max_x := x, x
			min_y, max_y := y, y

			for head < tail && island.tile_count < MAX_TILES {
				cx := queue[head][0]
				cy := queue[head][1]
				head += 1

				island.tiles[island.tile_count] = {i32(cx), i32(cy), false}
				island.tile_count += 1

				if cx < min_x {min_x = cx}
				if cx > max_x {max_x = cx}
				if cy < min_y {min_y = cy}
				if cy > max_y {max_y = cy}

				for d in dirs {
					nx := cx + d[0]
					ny := cy + d[1]
					if nx < 0 || nx >= grid.width || ny < 0 || ny >= grid.height {
						continue
					}
					if visited_at(visited_data, nx, ny)^ {continue}
					if grid.cells[ny][nx] != start_char {continue}

					visited_at(visited_data, nx, ny)^ = true
					if tail < MAX_TILES {
						queue[tail] = {nx, ny}
						tail += 1
					}
				}
			}

			// Center position in world space
			center_x := f32(min_x + max_x) / 2.0 * f32(TILE_SIZE)
			center_y := f32(min_y + max_y) / 2.0 * f32(TILE_SIZE)
			island.pos = {center_x, center_y}

			// Bounding radius for label placement
			half_w := f32(max_x - min_x) / 2.0 * f32(TILE_SIZE)
			half_h := f32(max_y - min_y) / 2.0 * f32(TILE_SIZE)
			island.radius = math.max(half_w, half_h)

			// Apply metadata if this island has a matching entry
			for m in 0 ..< meta_count {
				if metas[m].id == island_count {
					island.production = metas[m].production
					island.rate = metas[m].rate
					island.max_ware = metas[m].max_ware
					island.dock_level = metas[m].dock_level

					for j in 0 ..< metas[m].name_len {
						island.name[j] = metas[m].name[j]
					}
					island.name_len = metas[m].name_len
					break
				}
			}

			// Fallback defaults when no metadata matched
			if island.name_len == 0 {
				name_buf := fmt.tprintf("Island %d", island_count)
				n := min(len(name_buf), 31)
				for j in 0 ..< n {
					island.name[j] = name_buf[j]
				}
				island.name_len = n
				island.rate = 2.0
				island.max_ware = 100
				island.dock_level = 2
			}

			island_count += 1
		}
	}

	return island_count
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

// get_name returns a null-terminated cstring of the island's name.
get_name :: proc(island: Island) -> cstring {
	buf: [33]u8
	for j in 0 ..< island.name_len {
		buf[j] = island.name[j]
	}
	buf[island.name_len] = 0
	return cstring(&buf[0])
}

// ---------------------------------------------------------------------------
// Application state
// ---------------------------------------------------------------------------

// Player tracks the player's on-screen position and movement parameters.
Player :: struct {
	x:     f32,
	y:     f32,
	speed: f32,
	size:  f32,
}

// Ship is a moveable vessel that can only travel in water.
Ship :: struct {
	x:     f32,
	y:     f32,
	speed: f32,
	angle: f32,
}

// App is the top-level game state — islands, grid, camera, economy, and player.
App :: struct {
	islands:      [MAX_ISLANDS]Island,
	island_count: int,
	grid:         MapGrid,
	camera:       rl.Camera2D,
	selected:     int,
	money:        f32,
	time_day:     f32,
	scroll_tex:   rl.Texture2D,
	bg_color:     rl.Color,
	scroll_x:     f32,
	scroll_y:     f32,
	player:       Player,
	ship:         Ship,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

// main initialises the window, loads the map and metadata, then runs the
// game loop: update → render → ImGui → input.
main :: proc() {
	rl.SetConfigFlags({.WINDOW_RESIZABLE, .WINDOW_ALWAYS_RUN})
	rl.InitWindow(1280, 720, "Ocean Circuit")
	defer rl.CloseWindow()
	rl.SetTargetFPS(60)

	imgui.CreateContext(nil)
	defer imgui.DestroyContext(nil)
	io := imgui.GetIO()
	io.ConfigFlags |= {.NavEnableKeyboard}
	rlimgui.init()
	defer rlimgui.shutdown()

	// Load map from CSV
	app := new(App)
	defer free(app)
	if !load_map_csv(MAP_CSV_PATH, &app.grid) {
		fmt.println("ERROR: Could not load", MAP_CSV_PATH)
		return
	}

	// Load island tiles from CSV (no flood fill needed)
	app.island_count = load_islands_csv(ISLANDS_CSV_PATH, &app.grid, &app.islands)

	// Load metadata (names, rates, dock levels)
	metas: [MAX_ISLANDS]IslandMeta
	meta_count: int
	load_metadata_csv(META_CSV_PATH, &metas, &meta_count)

	// Apply metadata to islands
	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		for m in 0 ..< meta_count {
			if metas[m].id == island.id {
				island.production = metas[m].production
				island.rate = metas[m].rate
				island.max_ware = metas[m].max_ware
				island.dock_level = metas[m].dock_level
				for j in 0 ..< metas[m].name_len {
					island.name[j] = metas[m].name[j]
				}
				island.name_len = metas[m].name_len
				break
			}
		}
	}

	// Load port positions and mark tiles
	load_ports_csv(PORTS_CSV_PATH, &app.islands, app.island_count)

	app.money = 1000
	app.selected = -1

	// Spawn the player on the PORT island (fallback: first island)
	app.player.size = 20
	app.player.speed = 200
	spawn_island := -1
	for i in 0 ..< app.island_count {
		if app.islands[i].production == .PORT {
			spawn_island = i
			break
		}
	}
	if spawn_island < 0 && app.island_count > 0 {
		spawn_island = 0
	}

	if spawn_island >= 0 && app.islands[spawn_island].tile_count > 0 {
		// Place player on first tile
		t := app.islands[spawn_island].tiles[0]
		app.player.x = f32(t.gx) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
		app.player.y = f32(t.gy) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2

		// Place ship on water adjacent to a port tile
		app.ship.x = app.player.x
		app.ship.y = app.player.y
		app.ship.speed = 150
		dirs := [4][2]int{{1, 0}, {-1, 0}, {0, 1}, {0, -1}}
		for ti in 0 ..< app.islands[spawn_island].tile_count {
			if !app.islands[spawn_island].tiles[ti].is_port {continue}
			px := app.islands[spawn_island].tiles[ti].gx
			py := app.islands[spawn_island].tiles[ti].gy
			for d in dirs {
				wx := px + i32(d[0])
				wy := py + i32(d[1])
				if wx >= 0 && wx < i32(app.grid.width) && wy >= 0 && wy < i32(app.grid.height) && app.grid.cells[wy][wx] == '.' {
					app.ship.x = f32(wx) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
					app.ship.y = f32(wy) * f32(TILE_SIZE) + f32(TILE_SIZE) / 2
					break
				}
			}
			if is_water(&app.grid, app.ship.x, app.ship.y) {break}
		}
	}

	// Camera: centred on player, half-zoom
	app.camera.offset = {640, 360}
	app.camera.target = {app.player.x, app.player.y}
	app.camera.rotation = 0
	app.camera.zoom = 0.5

	// Tiled sea texture
	app.scroll_tex = rl.LoadTexture("assets/img/sea_texture.jpg")
	defer rl.UnloadTexture(app.scroll_tex)

	app.bg_color = {10, 20, 50, 255}

	fmt.printf("Loaded %d islands from %s\n", app.island_count, ISLANDS_CSV_PATH)

	// Main game loop
	for !rl.WindowShouldClose() {
		update_player(app)
		update_ship(app)
		update_camera(app)
		app.time_day += rl.GetFrameTime() / 60.0

		rl.BeginDrawing()
		rl.ClearBackground(app.bg_color)

		rl.BeginMode2D(app.camera)
		draw_water(app)
		draw_islands(app)
		draw_ship(app)
		draw_player(app)
		rl.EndMode2D()

		rlimgui.begin()
		draw_hud(app)
		rlimgui.end()

		if rl.IsMouseButtonPressed(.LEFT) && !imgui.GetIO().WantCaptureMouse {
			handle_click(app)
		}

		rl.EndDrawing()
	}
}

// ---------------------------------------------------------------------------
// Player movement
// ---------------------------------------------------------------------------

// is_water returns true if the world-space position falls on a water tile
// (or outside the grid bounds).
is_water :: proc(grid: ^MapGrid, world_x, world_y: f32) -> bool {
	gx := int(world_x / f32(TILE_SIZE))
	gy := int(world_y / f32(TILE_SIZE))
	if gx < 0 || gx >= grid.width || gy < 0 || gy >= grid.height {
		return true
	}
	return grid.cells[gy][gx] == '.'
}

// update_player reads WASD input and moves the player, blocking
// movement into non-water tiles.
update_player :: proc(app: ^App) {
	dt := rl.GetFrameTime()
	speed := app.player.speed * dt
	dx: f32 = 0
	dy: f32 = 0

	if rl.IsKeyDown(.W) {dy -= speed}
	if rl.IsKeyDown(.S) {dy += speed}
	if rl.IsKeyDown(.A) {dx -= speed}
	if rl.IsKeyDown(.D) {dx += speed}

	// Try X then Y independently so diagonal movement slides along walls
	new_x := app.player.x + dx
	if !is_water(&app.grid, new_x, app.player.y) {
		app.player.x = new_x
	}

	new_y := app.player.y + dy
	if !is_water(&app.grid, app.player.x, new_y) {
		app.player.y = new_y
	}
}

// update_ship is currently unused — ship is static at port.
update_ship :: proc(app: ^App) {
	_ = app
}

// ---------------------------------------------------------------------------
// Camera — free-form panning with arrow keys, zoom with scroll wheel
// ---------------------------------------------------------------------------

// update_camera centres the camera on the player and adjusts zoom
// with the mouse wheel (clamped to 0.5–1.5).
update_camera :: proc(app: ^App) {
	app.camera.target = {app.player.x, app.player.y}

	wheel := rl.GetMouseWheelMove()
	if wheel != 0 {
		app.camera.zoom += wheel * 0.05
		if app.camera.zoom < 0.5 {app.camera.zoom = 0.5}
		if app.camera.zoom > 1.5  {app.camera.zoom = 1.5}
	}
}

// ---------------------------------------------------------------------------
// Rendering — viewport culled for performance
// ---------------------------------------------------------------------------

// get_viewport returns the visible world-space rectangle based on the
// current camera position and zoom level.
get_viewport :: proc(app: ^App) -> (min_x, min_y, max_x, max_y: f32) {
	screen_w := f32(rl.GetScreenWidth())
	screen_h := f32(rl.GetScreenHeight())
	half_w := (screen_w / 2) / app.camera.zoom
	half_h := (screen_h / 2) / app.camera.zoom
	min_x = app.camera.target.x - half_w
	min_y = app.camera.target.y - half_h
	max_x = app.camera.target.x + half_w
	max_y = app.camera.target.y + half_h
	return
}

// draw_water tiles the sea texture across the visible viewport, slowly
// scrolling to give a sense of ocean movement.
draw_water :: proc(app: ^App) {
	tex_w := f32(app.scroll_tex.width)
	tex_h := f32(app.scroll_tex.height)

	app.scroll_x += 15 * rl.GetFrameTime()
	app.scroll_y += 10 * rl.GetFrameTime()
	if app.scroll_x >= tex_w {app.scroll_x -= tex_w}
	if app.scroll_y >= tex_h {app.scroll_y -= tex_h}

	vp_min_x, vp_min_y, vp_max_x, vp_max_y := get_viewport(app)
	start_ix := i32(math.floor(vp_min_x / tex_w)) - 1
	start_iy := i32(math.floor(vp_min_y / tex_h)) - 1
	end_ix := i32(math.ceil(vp_max_x / tex_w)) + 1
	end_iy := i32(math.ceil(vp_max_y / tex_h)) + 1

	for ix := start_ix; ix <= end_ix; ix += 1 {
		for iy := start_iy; iy <= end_iy; iy += 1 {
			pos_x := f32(ix) * tex_w - app.scroll_x
			pos_y := f32(iy) * tex_h - app.scroll_y
			rl.DrawTexture(app.scroll_tex, i32(pos_x), i32(pos_y), rl.WHITE)
		}
	}
}

// draw_islands renders every island's tiles and labels.
// Viewport culling skips tiles outside the camera view for performance.
draw_islands :: proc(app: ^App) {
	vp_min_x, vp_min_y, vp_max_x, vp_max_y := get_viewport(app)
	tile_f := f32(TILE_SIZE)

	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		color := resource_colors[island.production]

		// Bounding-box cull entire island if off-screen (with buffer)
		buffer := tile_f * 2
		island_min_x := island.pos.x - island.radius - buffer
		island_max_x := island.pos.x + island.radius + buffer
		island_min_y := island.pos.y - island.radius - buffer
		island_max_y := island.pos.y + island.radius + buffer
		if island_max_x < vp_min_x ||
		   island_min_x > vp_max_x ||
		   island_max_y < vp_min_y ||
		   island_min_y > vp_max_y {
			continue
		}

		// Draw tiles
		for t in 0 ..< island.tile_count {
			tile := &island.tiles[t]
			x := f32(tile.gx) * tile_f
			y := f32(tile.gy) * tile_f

			// Selection glow
			if app.selected == i {
				rl.DrawRectangle(
					i32(x) - 1,
					i32(y) - 1,
					i32(tile_f) + 2,
					i32(tile_f) + 2,
					{255, 255, 100, 60},
				)
			}

			// Port tiles get a distinct colour; resource tiles keep theirs
			tile_color := color
			if tile.is_port {
				tile_color = PORT_COLOR
			}

			rl.DrawRectangleV({x, y}, {tile_f, tile_f}, tile_color)
			rl.DrawRectangleLinesEx({x, y, tile_f, tile_f}, 2, {20, 20, 20, 200})
		}

		// Labels (only when roughly on-screen)
		if island.pos.x >= vp_min_x - 200 &&
		   island.pos.x <= vp_max_x + 200 &&
		   island.pos.y >= vp_min_y - 100 &&
		   island.pos.y <= vp_max_y + 100 {

			name := get_name(island^)
			text_w := rl.MeasureText(name, 32)
			name_x := i32(island.pos.x) - text_w / 2
			name_y := i32(island.pos.y + island.radius + 16)
			rl.DrawText(name, name_x + 2, name_y + 2, 32, {0, 0, 0, 200})
			rl.DrawText(name, name_x, name_y, 32, {255, 255, 255, 255})

			res_name := resource_names[island.production]
			res_w := rl.MeasureText(res_name, 24)
			res_x := i32(island.pos.x) - res_w / 2
			res_y := i32(island.pos.y - 20)
			rl.DrawText(res_name, res_x + 2, res_y + 2, 24, {0, 0, 0, 200})
			rl.DrawText(res_name, res_x, res_y, 24, {255, 255, 255, 255})
		}
	}
}

// draw_ship renders the ship as a pink rectangle, 3 tiles tall and 1 tile wide,
// placed at the port. The ship is static — not controlled by the player.
draw_ship :: proc(app: ^App) {
	tile_f := f32(TILE_SIZE)
	ship_w := tile_f
	ship_h := tile_f * 3

	origin := rl.Vector2{ship_w / 2, ship_h / 2}
	rect := rl.Rectangle{
		app.ship.x - origin.x,
		app.ship.y - origin.y,
		ship_w,
		ship_h,
	}

	rl.DrawRectanglePro(rect, origin, app.ship.angle, {255, 100, 150, 255})
	rl.DrawRectangleLinesEx(rect, 2, {200, 60, 100, 255})
}

// draw_player renders the player as a small red square at its center position.
draw_player :: proc(app: ^App) {
	s := app.player.size
	rl.DrawRectangleV({app.player.x - s / 2, app.player.y - s / 2}, {s, s}, {220, 30, 30, 255})
}

// ---------------------------------------------------------------------------
// HUD — ImGui panels
// ---------------------------------------------------------------------------

// draw_hud draws the top-left info panel and, when an island is selected,
// a detail panel showing its production, warehouse, and dock stats.
draw_hud :: proc(app: ^App) {
	// Info panel
	imgui.SetNextWindowSize({260, 0}, .FirstUseEver)
	imgui.SetNextWindowPos({10, 10}, .FirstUseEver)
	if imgui.Begin("Info") {
		imgui.Text("Map: %dx%d", MAP_WIDTH, MAP_HEIGHT)
		imgui.Text("Islands: %d", app.island_count)
		imgui.TextColored({0.2, 1, 0.2, 1}, "Money: $%d", i32(app.money))
		imgui.Text("Day: %.1f", app.time_day)
		imgui.Text("Zoom: %.0f%%", app.camera.zoom * 100)
		imgui.Separator()
		imgui.TextDisabled("WASD: move character")
		imgui.TextDisabled("Scroll: zoom")
		imgui.TextDisabled("Click: select island or ship")
		imgui.TextDisabled("Scroll: zoom")
	}
	imgui.End()

	// Selected-island detail panel
	if app.selected >= 0 && app.selected < app.island_count {
		island := &app.islands[app.selected]
		name := get_name(island^)

		imgui.SetNextWindowSize({280, 0}, .FirstUseEver)
		imgui.SetNextWindowPos({10, 120}, .FirstUseEver)
		if imgui.Begin("Island") {
			imgui.Text("ID: %d | %s", island.id, name)
			imgui.Separator()
			imgui.Text("Produces: %s", resource_names[island.production])
			imgui.Text("Rate: %.1f/day", island.rate)
			imgui.Text("Storage: %.0f / %.0f", island.warehouse, island.max_ware)
			imgui.Text("Dock Level: %d", island.dock_level)
			imgui.Text("Tiles: %d", island.tile_count)

			if island.port_count > 0 {
				imgui.Separator()
				imgui.TextColored({0, 0.9, 0.8, 1}, "Port Tiles: %d", island.port_count)
				imgui.TextDisabled("Docks along the coast")
			}
		}
		imgui.End()
	}

	// Selected-ship detail panel
	if app.selected == -2 {
		imgui.SetNextWindowSize({280, 0}, .FirstUseEver)
		imgui.SetNextWindowPos({10, 120}, .FirstUseEver)
		if imgui.Begin("Ship") {
			imgui.TextColored({1, 0.4, 0.6, 1}, "Explorer")
			imgui.Separator()
			imgui.TextDisabled("Ship to explore")
			imgui.Separator()
			imgui.Text("Speed: %.0f", app.ship.speed)
		}
		imgui.End()
	}
}

// ---------------------------------------------------------------------------
// Input — click to select an island
// ---------------------------------------------------------------------------

// handle_click converts the mouse position to world space and checks
// every island tile for a hit, selecting the first match.
handle_click :: proc(app: ^App) {
	mouse := rl.GetScreenToWorld2D(rl.GetMousePosition(), app.camera)
	app.selected = -1
	tile_f := f32(TILE_SIZE)

	// Check ship hit
	ship_w := tile_f
	ship_h := tile_f * 3
	if mouse.x >= app.ship.x - ship_w / 2 && mouse.x <= app.ship.x + ship_w / 2 &&
	   mouse.y >= app.ship.y - ship_h / 2 && mouse.y <= app.ship.y + ship_h / 2 {
		app.selected = -2
		return
	}

	for i in 0 ..< app.island_count {
		island := &app.islands[i]
		for t in 0 ..< island.tile_count {
			tile := &island.tiles[t]
			tx := f32(tile.gx) * tile_f
			ty := f32(tile.gy) * tile_f
			if mouse.x >= tx && mouse.x <= tx + tile_f &&
			   mouse.y >= ty && mouse.y <= ty + tile_f {
				app.selected = i
				return
			}
		}
	}
}
